version: 2.1
orbs:
  docker: circleci/docker@1.7.0
  snyk: snyk/snyk@1.1.1
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  docker-build:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    environment:
      IMAGE_NAME: tomgonzo/hawkdog
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t $IMAGE_NAME .
      - snyk/scan:
          docker-image-name: '$IMAGE_NAME:latest'
          fail-on-issues: false
          monitor-on-build: true
          project: '${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}-container'
          severity-threshold: high
          target-file: Dockerfile
          token-variable: SNYK_TOKEN
workflows:
  build-and-scan:
    jobs:
      - docker-build
