name: HawkScan
on:
  repository_dispatch:
    types: [integration-initial-test]
jobs:
  hawkscan:
    name: HawkScan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose up -d
      - name: Checkout vulny repo
        run: git pull https://github.com/kaakaww/javaspringvulny.git
      - uses: stackhawk/hawkscan-action@main
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
          configurationFiles: stackhawk.yml
          sourceURL: ${{ secrets.HAWK_CLI_SOURCE_URL }}
          version: 2.2.0
        env:
          APP_ID: ae764fec-e001-4f4a-b4b4-85aaf8f0605c
