name: HawkScan
on:
  push:
  pull_request:
jobs:
  hawkscan:
    name: HawkScan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose up -d
      - uses: stackhawk/hawkscan-action@main
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
          configurationFiles: stackhawk.yml stackhawk-jsv-form-cookie.yml
          sourceURL: https://download.test.stackhawk.com/hawk/cli
          # version: 2.2.0-beta
        env:
          APP_ID: ae764fec-e001-4f4a-b4b4-85aaf8f0605c
